packaging_format = 2

id = "openproject"
name = "OpenProject"
description.en = "Web-based project management software"
description.fr = "Logiciel de gestion de projet basé sur le web"

version = "10.5.1~ynh1"

maintainers = ["Moutonjr \"Geoff\""]

[upstream]
license = "GPL-3.0-or-later"
website = "https://www.openproject.org/"
admindoc = "https://www.openproject.org/docs/"
code = "https://github.com/opf/openproject"

[integration]
yunohost = ">= 11.1.19"
architectures = "all"
multi_instance = false
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"
    full_domain = true

    [install.init_main_permission]
    help.en = "A public Openproject app could be less secure depending your configuration. Butit can allow external people from your Yunohost instance to participate to project management."
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "string"
    choices = ["fr", "en"]
    default = "en"

[resources]

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
    api.url = "/api"
    api.allowed = "visitors"
    api.auth_header = false
    api.show_tile = false
    api.protected = true

    [resources.apt]
    packages = "apt-transport-https memcached postgresql postgresql-common"

    extras.openproject.repo = "deb https://dl.packager.io/srv/deb/opf/openproject/stable/12/debian bullseye main"
    extras.openproject.key = "https://dl.packager.io/srv/opf/openproject/key"
    extras.openproject.packages = "openproject"

    [resources.database]
    type = "postgresql"
